#!/bin/bash
source .env

docker build \
  --build-arg VERSION=${VERSION} \
  --build-arg OWNCLOUD_TARBALL=${OWNCLOUD_TARBALL} \
  --build-arg RICHDOCUMENTS_TARBALL=${RICHDOCUMENTS_TARBALL} \
  --build-arg RICHDOCUMENTS_CHECKSUM=${RICHDOCUMENTS_CHECKSUM} \
  --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --build-arg VCS_REF=$(git rev-parse --short HEAD) \
  -t ${IMAGE_NAME} .
